server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.175.175:3306/zookeeper?useUnicode=true&characterEncoding=utf-8
    username: liteng
    password: 123456